# Site settings
title: Mônica Bulgari
motto: Journalist, Linguist, Social Scientist, Feminist
email: monica@monicabulgari.com
description: Mônica Bulgari is a Journalist, Feminist, Social Scientist and Linguistics researcher
  Social Scientist. Currently works as Social Media Analyst at São Paulo
  city hall.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://monicabulrai.github.io" # the base hostname & protocol for your site
twitter_username: monicabulgari
github_username:  monicabulgari

# Build settings
markdown: kramdown
